### ISSUE TITLE
Gibt es eine API Erklärung 

### ISSUE THREAD

**Issue by PlayDiver** [CodeKing/de.codeking.symcon.oilfox#1]
Wie ich im Code erkennen könnte, geht dein Projekt über eine REST-Schnittstelle.
Ich würde gerne für meinen ioBroker einen Adapter schreiben, der mir den Füllstand anzeigt, so das ich das in meine Virtualisierung übernehmen kann.

Daher die Frage jetzt, gibt es eine API Erklärung ?

Schon mal danke, dass du dir es durchgelesen hast.

**Comment by CodeKing** [comment]
Hallo,

eine API Dokumentation gibt es leider nicht, ich habe das Ganze auch nur aus der Kommunikation der App entnommen.

Ansich ist die REST API aber recht einfach gestrickt und bietet nach dem Login mit einem Oilfox Account alle hinterlegten Daten im JSON Format zurück.

Viele Grüße,

Frank

**Comment by PlayDiver** [comment]
Okey, Danke. von Welcher App hast du die Infos dann ?

**Comment by CodeKing** [comment]
Von der offiziellen Android App, die Kommunikation habe ich dann mit Wireshark mitgelesen.

**Comment by PlayDiver** [comment]
omg, das geht. Schicken die das nicht per https raus ?

Ich lese mich mal in dein Code weiter ein, denke das musste ja ausrechen

**Comment by CodeKing** [comment]
Ich glaube mittlerweile geht das nicht mehr, in der v1 der API war das aber problemlos möglich :)

**Comment by PlayDiver** [comment]
Okey, danke. Ich werde es mal versuchen.

**Comment by jogibear9988** [comment]
@CodeKing hast du auch Probleme das es seit 2 Tagen nicht mehr geht?
